### ISSUE TITLE
Example doesn't build

### ISSUE THREAD

**Issue by andrewrch** [amzn/hawktracer#11]
Since it includes hawktracer.h, which requires config.h, the example doesn't build as config.h is installed to the lib/include directory.

**Comment by loganek** [comment]
Thanks @andrewrch for the report. Could you post here your configuration and build commands? The example should compile, as for hawktracer target we define following include directories:
```cmake
target_include_directories(hawktracer PUBLIC
        "$<BUILD_INTERFACE:${HAWKTRACER_INCLUDE_DIRS}>"
        $<INSTALL_INTERFACE:include>)
```
Where `HAWKTRACER_INCLUDE_DIRS` is set to `"${CMAKE_CURRENT_SOURCE_DIR}/include" "${CMAKE_CURRENT_BINARY_DIR}/include"`

**Comment by andrewrch** [comment]
You're right, I removed the build dir and started from scratch and it works fine. Thanks
