### ISSUE TITLE
Flushing API for file_dump_listener

### ISSUE THREAD

**Issue by ftanuma** [amzn/hawktracer#51]
In some situation, I would like to trigger flushing all the data so far in file_dump_listener. By looking at current implementation, listener doesn't flush until its buffer is full.

It would be great if there is an API to trigger flushing.
Thanks!

**Comment by loganek** [comment]
@ftanuma thanks for the report. The API has been implemented in 6a0420d95fb341010cae97911804ddc331ec4f38
