### ISSUE TITLE
The return value of 'sscanf()' should be checked

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [amzn/hawktracer#53]
https://github.com/amzn/hawktracer/blob/6a0420d95fb341010cae97911804ddc331ec4f38/lib/platform/linux/cpu_usage.c#L56

The return value of 'sscanf()' should be checked  before continuing to execute the program

**Comment by loganek** [comment]
Thanks for the report, the issue has been fixed in fd754b40260a9a03aacae9c43204c3235ba92e0e
