### ISSUE TITLE
amalgamate.py fails with a encoding/decoding error

### ISSUE THREAD

**Issue by lu-zero** [amzn/hawktracer#65]
```
Generate source file /usr/src/hawktracer/.build/hawktracer.cpp
Traceback (most recent call last):
  File "/usr/src/hawktracer/tools/amalgamate.py", line 308, in <module>
    run_program(sys.argv[1:])
  File "/usr/src/hawktracer/tools/amalgamate.py", line 304, in run_program
    Amalgamator(args.root_dir, header_file, source_file).generate()
  File "/usr/src/hawktracer/tools/amalgamate.py", line 284, in generate
    self._generate_source_file()
  File "/usr/src/hawktracer/tools/amalgamate.py", line 276, in _generate_source_file
    source_file_dumper.dump_file(os.path.join(self._lib_dir, source_file))
  File "/usr/src/hawktracer/tools/amalgamate.py", line 216, in dump_file
    for line in f:
  File "/usr/lib64/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3101: ordinal not in range(128)
```

```
python --version
Python 3.5.9
```
On bb3a3ac881180db0e265619dfd8410928fc6be6c

**Comment by loganek** [comment]
Thanks @lu-zero for the report. I've checked on my environment and couldn't reproduce the issue. Could you please provide more details about the operating system you're running the command on?
Also, could you try the following command in your `.build` directory and see if the result is the same?
```
python3 ../tools/amalgamate.py --root-dir .. --out-dir . --config-path lib/include/hawktracer/ht_config.h  --cpp
```
Thank you

**Comment by lu-zero** [comment]
I doublechecked and the problem is that apparently if your locale is POSIX and not POSIX.utf-8 the read-file-by-line iterator crashes horribly.

The workaround is to set a `POSIX.utf-8` locale.

**Comment by loganek** [comment]
The real problem was that in the source code we had non-ascii characters (0xe2) which shouldn't be there. I removed them and the script works fine even with `POSIX` locale.
@lu-zero again thanks a lot for the report, and sorry for inconvenience
