### ISSUE TITLE
Track buildroot integration

### ISSUE THREAD

**Issue by gtalis** [amzn/hawktracer#78]
This issue is used to track the progress of the integration of the tool within buildroot.
Patch was sent to mailing-list (next branch). Will be closed when integrated in mainline:
http://patchwork.ozlabs.org/project/buildroot/patch/20200517123726.81405-1-gilles.talis@gmail.com/

**Comment by loganek** [comment]
@gtalis is there any progress on that? Many thanks :)

**Comment by ffontaine** [comment]
hawktracer has been integrated in buildroot in July 2022: https://git.buildroot.net/buildroot/commit/package?id=94d8764ef938936aa5432f1f13bd1b2d8b62a159 so I assume that this issue can be closed

**Comment by loganek** [comment]
Yes, thanks.
