### ISSUE TITLE
Dynamic tracepoints mapping not found

### ISSUE THREAD

**Issue by AlexEne** [amzn/hawktracer#81]
Hello,

I'm trying to get dynamic tracepoints to work and it seems I can't capture the dynamic tracepoints correctly by connecting through TCP (tried with `v10.0` and `master` branch).

I am calling in order something along the lines of:

```cpp
ht_feature_cached_string_add_mapping_dynamic(ht_global_timeline_get(), name);

while(true) {
    ht_feature_callstack_start_int(ht_global_timeline_get(), custom_id);
    ht_feature_callstack_stop(ht_global_timeline_get());
}
```

hawktracer-converter prints: `Cannot find mapping for label` for all labels that are dynamic.

Extra details: 
* I am connecting `hawktracer-converter` **after** calling `ht_feature_cached_string_add_mapping_dynamic`. If `hawktracer-converter` is started first, it will miss all tracepoints and never connect to the server. Not sure if it's expected. I'm on OSX)
* I also emit some scoped tracepoints emitted that work (by using a mapping file).

**Comment by AlexEne** [comment]
After some investigation it seems things work if the client is connected when `ht_feature_cached_string_add_mapping_dynamic` is called.

**Comment by loganek** [comment]
Hi @AlexEne indeed, mapping is automatically being pushed to the listener only if it's created after creating the listener. The recommendation is to call `ht_feature_cached_string_push_map(ht_global_timeline_get())` just after your client gets connected. Please note it's safe to call `ht_feature_cached_string_push_map` multiple times for the same timeline (in case you have more than one client), as client should handle the duplication.

I agree this feature is not well documented, so I'll update the documentation. Please let me know if that solves your problem.

**Comment by loganek** [comment]
The documentation is updated for [master branch](https://www.hawktracer.org/doc/master/feature__cached__string_8h.html#a4cd8161a87508115767de52a6976afb8)
Commit: https://github.com/amzn/hawktracer/commit/c2dcd1ac4b08c1d6ce3d4978dcd63aa1616bb5ae

I'm closing the issue for now, but please don't hesitate to reopen it if you have more questions. Also, feel free to open a new issue if you experience any problems with HawkTracer.

Many thanks for your report!
