### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by lu-zero** [amzn/hawktracer#87]
The website is still down.

**Comment by loganek** [comment]
Hi,
Thanks a lot for the report. The website was a community sponsored/driven, and due to lack of sponsorship it's currently inactive. I'll speak to Amazon if there's interest in owning the domain and get back to you soon.

**Comment by lu-zero** [comment]
Switching to hawktracer.github.io might be a good solution maybe?

**Comment by loganek** [comment]
I think that's a good idea. I opened a PR, will merge it once DNS is updated.
