### ISSUE TITLE
Build failure with gcc 12

### ISSUE THREAD

**Issue by ffontaine** [amzn/hawktracer#89]
We have the following build failures on buildroot autobuilders with gcc 12:

```
/tmp/instance-8/output-1/build/hawktracer-2ec19d71923344148928ef45fce549eda67030a4/hawktracer.cpp: In function 'HT_Thread* ht_thread_create(ht_thread_callback_t, void*)':
/tmp/instance-8/output-1/build/hawktracer-2ec19d71923344148928ef45fce549eda67030a4/hawktracer.cpp:1006:28: error: no matching function for call to 'operator new(sizetype, std::thread*)'
 1006 |     new(&th->th) HT_Thread();
      |                            ^
```

Full build log: http://autobuild.buildroot.org/results/d18/d18a1b2ee6cdcb289567ae90b2d836844427b5f6/build-end.log

However, I don't know how to fix it properly, any advise is appreciated.

**Comment by loganek** [comment]
Thanks, I fixed that in https://github.com/amzn/hawktracer/pull/90
